package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/javanhut/genesys/pkg/config"
	"github.com/javanhut/genesys/pkg/intent"
	"github.com/javanhut/genesys/pkg/planner"
	"github.com/javanhut/genesys/pkg/provider"
	providerTypes "github.com/javanhut/genesys/pkg/provider"
	"github.com/javanhut/genesys/pkg/provider/aws"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	applyFlag    bool
	dryRunFlag   bool
	configFile   string
	providerName string
	region       string
	outputFormat string
)

// NewExecuteCommand creates the execute command
func NewExecuteCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "execute [config-file.yaml | intent]",
		Short: "Deploy or delete resources from configuration files",
		Long: `Deploy or delete cloud resources from configuration files generated by interactive mode.
Supports dry-run for safe preview before deployment.

Examples:
  genesys execute config.yaml                    # Deploy resources from config
  genesys execute config.yaml --dry-run          # Preview changes without deployment
  genesys execute deletion config.yaml           # Delete resources from config
  genesys execute deletion config.yaml --dry-run # Preview deletion

Legacy intent-based usage (for backwards compatibility):
  genesys execute bucket my-bucket --apply       # Create bucket from intent
  genesys execute static-site --apply            # Deploy static site`,
		Args: cobra.ArbitraryArgs,
		RunE: runExecute,
	}

	cmd.Flags().BoolVar(&applyFlag, "apply", false, "Apply the changes (default is preview only)")
	cmd.Flags().BoolVar(&dryRunFlag, "dry-run", false, "Show what would be done without making changes")
	cmd.Flags().StringVarP(&configFile, "config", "c", "", "Configuration file (YAML or TOML)")
	cmd.Flags().StringVar(&providerName, "provider", "aws", "Cloud provider (aws|gcp|azure)")
	cmd.Flags().StringVar(&region, "region", "", "Cloud region")
	cmd.Flags().StringVarP(&outputFormat, "output", "o", "human", "Output format (human|json)")

	return cmd
}

func runExecute(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Handle special deletion case
	if len(args) >= 2 && args[0] == "deletion" {
		configFile = args[1]
		return executeDeletion(ctx, configFile)
	}

	// Handle direct config file execution (e.g., "genesys execute bucket.yaml")
	if len(args) == 1 && (strings.HasSuffix(args[0], ".yaml") || strings.HasSuffix(args[0], ".yml") || strings.HasSuffix(args[0], ".toml")) {
		configFile = args[0]
		return executeConfigFile(ctx, configFile)
	}

	// Load configuration if provided via --config flag
	var cfg *config.Config
	if configFile != "" {
		var err error
		cfg, err = config.LoadConfig(configFile)
		if err != nil {
			return fmt.Errorf("failed to load config: %w", err)
		}
	} else {
		// Create default config from flags
		cfg = &config.Config{
			Provider: providerName,
			Region:   region,
		}
	}

	// If we have a config file but no command line intent, execute based on config
	if configFile != "" && len(args) == 0 {
		return executeFromConfig(ctx, cfg)
	}

	// Parse the intent from command line arguments
	if len(args) == 0 {
		return fmt.Errorf("no intent specified. Usage: genesys execute <config-file.yaml> or genesys execute <intent>")
	}

	parser := intent.NewParser()
	parsedIntent, err := parser.Parse(args)
	if err != nil {
		return fmt.Errorf("failed to parse intent: %w", err)
	}

	// Get the provider
	p, err := provider.Get(cfg.Provider, map[string]string{
		"region": cfg.Region,
	})
	if err != nil {
		// For now, create a mock provider for testing
		fmt.Printf("Note: Using mock provider (real provider not yet implemented)\n\n")
		p = provider.NewMockProvider(cfg.Provider, cfg.Region)
	}

	// Create planner
	plnr := planner.New(p)

	// Generate plan
	plan, err := plnr.PlanFromIntent(ctx, parsedIntent)
	if err != nil {
		return fmt.Errorf("failed to generate plan: %w", err)
	}

	// Display plan
	if outputFormat == "json" {
		fmt.Println(plan.ToJSON())
	} else {
		fmt.Println(plan.ToHumanReadable())
	}

	// Apply if requested
	if applyFlag {
		fmt.Println("\nApplying changes...")
		// TODO: Implement executor
		fmt.Println("Executor not yet implemented - this is a preview of what would happen")
	} else {
		fmt.Println("\nNote: This is a preview. Use --apply to make these changes.")
	}

	return nil
}

// executeFromConfig executes based on configuration file content
func executeFromConfig(ctx context.Context, cfg *config.Config) error {
	fmt.Println("Executing from configuration file...")
	
	// Get the provider
	p, err := provider.Get(cfg.Provider, map[string]string{
		"region": cfg.Region,
	})
	if err != nil {
		// For now, create a mock provider for testing
		fmt.Printf("Note: Using mock provider (real provider not yet implemented)\n\n")
		p = provider.NewMockProvider(cfg.Provider, cfg.Region)
	}

	// Create planner (for future use)
	_ = planner.New(p)

	// Process outcomes if they exist
	if len(cfg.Outcomes) > 0 {
		for name, outcome := range cfg.Outcomes {
			fmt.Printf("Processing outcome: %s\n", name)
			// For now, just show what would be planned
			fmt.Printf("- Type: %s\n", name)
			if outcome.Domain != "" {
				fmt.Printf("- Domain: %s\n", outcome.Domain)
			}
			if outcome.Runtime != "" {
				fmt.Printf("- Runtime: %s\n", outcome.Runtime)
			}
			fmt.Println()
		}
	}

	// Process resources if they exist
	if len(cfg.Resources.Compute) > 0 || len(cfg.Resources.Storage) > 0 || 
	   len(cfg.Resources.Database) > 0 || len(cfg.Resources.Serverless) > 0 {
		
		fmt.Println("Processing resources from configuration:")
		
		// Process compute resources
		for _, compute := range cfg.Resources.Compute {
			fmt.Printf("- Compute: %s (%s, count: %d)\n", compute.Name, compute.Type, compute.Count)
		}
		
		// Process storage resources  
		for _, storage := range cfg.Resources.Storage {
			fmt.Printf("- Storage: %s (%s)\n", storage.Name, storage.Type)
		}
		
		// Process database resources
		for _, database := range cfg.Resources.Database {
			fmt.Printf("- Database: %s (%s %s, %dGB)\n", database.Name, database.Engine, database.Size, database.Storage)
		}
		
		// Process serverless resources
		for _, serverless := range cfg.Resources.Serverless {
			fmt.Printf("- Function: %s (%s, %dMB)\n", serverless.Name, serverless.Runtime, serverless.Memory)
		}
		
		fmt.Println()
		fmt.Println("Note: Full resource execution from config not yet implemented")
	}

	return nil
}

// executeConfigFile handles execution of S3 and other config files
func executeConfigFile(ctx context.Context, configPath string) error {
	// Check if file exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return fmt.Errorf("configuration file does not exist: %s", configPath)
	}

	// Try to parse as S3 config first
	if isS3Config(configPath) {
		return executeS3Config(ctx, configPath)
	}

	// Fall back to generic config execution
	fmt.Printf("Executing configuration file: %s\n", configPath)
	fmt.Println("Generic config execution not yet implemented")
	return nil
}

// isS3Config checks if the file is an S3 bucket configuration
func isS3Config(configPath string) bool {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return false
	}

	// Check if it contains S3-specific keys
	content := string(data)
	return strings.Contains(content, "provider: aws") && 
		   strings.Contains(content, "storage:") && 
		   (strings.Contains(content, "bucket") || strings.Contains(content, "type: bucket"))
}

// executeS3Config handles S3 bucket configuration
func executeS3Config(ctx context.Context, configPath string) error {
	// Load S3 configuration
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read configuration file: %w", err)
	}

	var s3Config config.S3BucketConfig
	if err := yaml.Unmarshal(data, &s3Config); err != nil {
		return fmt.Errorf("failed to parse S3 configuration: %w", err)
	}

	bucketName := s3Config.Resources.Storage[0].Name
	
	if dryRunFlag {
		fmt.Printf("🔍 Dry run for S3 bucket configuration: %s\n", filepath.Base(configPath))
		fmt.Println("===============================================")
		fmt.Printf("\nWhat would be created:\n")
		fmt.Printf("  Bucket Name: %s\n", bucketName)
		fmt.Printf("  Provider: %s\n", s3Config.Provider)
		fmt.Printf("  Region: %s\n", s3Config.Region)
		fmt.Printf("  Versioning: %v\n", s3Config.Resources.Storage[0].Versioning)
		fmt.Printf("  Encryption: %v\n", s3Config.Resources.Storage[0].Encryption)
		fmt.Printf("  Public Access: %v\n", s3Config.Resources.Storage[0].PublicAccess)
		if len(s3Config.Resources.Storage[0].Tags) > 0 {
			fmt.Printf("  Tags:\n")
			for k, v := range s3Config.Resources.Storage[0].Tags {
				fmt.Printf("    %s: %s\n", k, v)
			}
		}
		fmt.Printf("\nNo actual changes would be made.\n")
		return nil
	}

	fmt.Printf("🚀 Deploying S3 bucket from: %s\n", filepath.Base(configPath))
	fmt.Println("======================================")
	fmt.Println()

	// Check AWS credentials
	interactiveConfig, err := config.NewInteractiveConfig()
	if err != nil {
		return fmt.Errorf("failed to initialize configuration: %w", err)
	}

	_, err = interactiveConfig.LoadProviderConfig("aws")
	if err != nil {
		return fmt.Errorf("AWS not configured. Run 'genesys config setup' to configure AWS credentials")
	}

	// Create AWS provider
	provider, err := aws.NewAWSProvider(s3Config.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS provider: %w", err)
	}

	// Get storage service
	storageService := provider.Storage()
	
	// Get bucket configuration
	bucketResource := s3Config.Resources.Storage[0]
	
	// Create bucket configuration
	bucketConf := &providerTypes.BucketConfig{
		Name:         bucketResource.Name,
		Versioning:   bucketResource.Versioning,
		Encryption:   bucketResource.Encryption,
		PublicAccess: bucketResource.PublicAccess,
		Tags:         bucketResource.Tags,
	}
	
	// Create bucket
	bucket, err := storageService.CreateBucket(ctx, bucketConf)
	if err != nil {
		return fmt.Errorf("failed to create S3 bucket: %w", err)
	}

	fmt.Printf("✅ S3 bucket '%s' created successfully!\n", bucket.Name)
	fmt.Printf("Region: %s\n", s3Config.Region)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  • View bucket: aws s3 ls s3://" + bucketName)
	fmt.Printf("  • Delete bucket: genesys execute deletion %s\n", filepath.Base(configPath))

	return nil
}

// executeDeletion handles deletion of resources
func executeDeletion(ctx context.Context, configPath string) error {
	// Check if file exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return fmt.Errorf("configuration file does not exist: %s", configPath)
	}

	// Try to parse as S3 config first
	if isS3Config(configPath) {
		return executeS3Deletion(ctx, configPath)
	}

	fmt.Printf("Deletion for configuration file '%s' not yet implemented\n", configPath)
	return nil
}

// executeS3Deletion handles S3 bucket deletion
func executeS3Deletion(ctx context.Context, configPath string) error {
	// Load S3 configuration
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read configuration file: %w", err)
	}

	var s3Config config.S3BucketConfig
	if err := yaml.Unmarshal(data, &s3Config); err != nil {
		return fmt.Errorf("failed to parse S3 configuration: %w", err)
	}

	bucketName := s3Config.Resources.Storage[0].Name

	if dryRunFlag {
		fmt.Printf("🔍 Dry run for S3 bucket deletion: %s\n", filepath.Base(configPath))
		fmt.Println("===========================================")
		fmt.Printf("\nWhat would be deleted:\n")
		fmt.Printf("  Bucket Name: %s\n", bucketName)
		fmt.Printf("  Region: %s\n", s3Config.Region)
		fmt.Printf("\nNo actual changes would be made.\n")
		return nil
	}

	fmt.Printf("⚠️  About to delete S3 bucket: %s\n", bucketName)
	fmt.Printf("Region: %s\n", s3Config.Region)
	fmt.Println()
	fmt.Println("This action cannot be undone!")

	// Create AWS provider
	provider, err := aws.NewAWSProvider(s3Config.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS provider: %w", err)
	}

	// Get storage service
	storageService := provider.Storage()

	// Delete bucket
	if err := storageService.DeleteBucket(ctx, bucketName); err != nil {
		return fmt.Errorf("failed to delete S3 bucket: %w", err)
	}

	fmt.Printf("✅ S3 bucket '%s' deleted successfully!\n", bucketName)
	return nil
}