package commands

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
	"github.com/javanhut/genesys/pkg/config"
	"github.com/javanhut/genesys/pkg/intent"
	"github.com/javanhut/genesys/pkg/planner"
	"github.com/javanhut/genesys/pkg/provider"
	providerTypes "github.com/javanhut/genesys/pkg/provider"
	"github.com/javanhut/genesys/pkg/provider/aws"
	"github.com/javanhut/genesys/pkg/state"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	applyFlag       bool
	dryRunFlag      bool
	forceDeletion   bool
	configFile      string
	providerName    string
	region          string
	outputFormat    string
)

// NewExecuteCommand creates the execute command
func NewExecuteCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "execute [config-file.yaml | intent]",
		Short: "Deploy or delete resources from configuration files",
		Long: `Deploy or delete cloud resources from configuration files generated by interactive mode.
Supports dry-run for safe preview before deployment.

Examples:
  genesys execute config.yaml                           # Deploy resources from config
  genesys execute config.yaml --dry-run                 # Preview changes without deployment
  genesys execute deletion config.yaml                  # Delete resources from config
  genesys execute deletion config.yaml --dry-run        # Preview deletion
  genesys execute deletion config.yaml --force-deletion # Force delete including all versions

Legacy intent-based usage (for backwards compatibility):
  genesys execute bucket my-bucket --apply       # Create bucket from intent
  genesys execute static-site --apply            # Deploy static site`,
		Args: cobra.ArbitraryArgs,
		RunE: runExecute,
	}

	cmd.Flags().BoolVar(&applyFlag, "apply", false, "Apply the changes (default is preview only)")
	cmd.Flags().BoolVar(&dryRunFlag, "dry-run", false, "Show what would be done without making changes")
	cmd.Flags().BoolVar(&forceDeletion, "force-deletion", false, "Force delete bucket contents including all versions (use with deletion)")
	cmd.Flags().StringVarP(&configFile, "config", "c", "", "Configuration file (YAML or TOML)")
	cmd.Flags().StringVar(&providerName, "provider", "aws", "Cloud provider (aws|gcp|azure)")
	cmd.Flags().StringVar(&region, "region", "", "Cloud region")
	cmd.Flags().StringVarP(&outputFormat, "output", "o", "human", "Output format (human|json)")

	return cmd
}

func runExecute(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Handle special deletion case
	if len(args) >= 2 && args[0] == "deletion" {
		configFile = args[1]
		return executeDeletion(ctx, configFile)
	}

	// Handle direct config file execution (e.g., "genesys execute bucket.yaml")
	if len(args) == 1 && (strings.HasSuffix(args[0], ".yaml") || strings.HasSuffix(args[0], ".yml") || strings.HasSuffix(args[0], ".toml")) {
		configFile = args[0]
		return executeConfigFile(ctx, configFile)
	}

	// Load configuration if provided via --config flag
	var cfg *config.Config
	if configFile != "" {
		var err error
		cfg, err = config.LoadConfig(configFile)
		if err != nil {
			return fmt.Errorf("failed to load config: %w", err)
		}
	} else {
		// Create default config from flags
		cfg = &config.Config{
			Provider: providerName,
			Region:   region,
		}
	}

	// If we have a config file but no command line intent, execute based on config
	if configFile != "" && len(args) == 0 {
		return executeFromConfig(ctx, cfg)
	}

	// Parse the intent from command line arguments
	if len(args) == 0 {
		return fmt.Errorf("no intent specified. Usage: genesys execute <config-file.yaml> or genesys execute <intent>")
	}

	parser := intent.NewParser()
	parsedIntent, err := parser.Parse(args)
	if err != nil {
		return fmt.Errorf("failed to parse intent: %w", err)
	}

	// Get the provider
	p, err := provider.Get(cfg.Provider, map[string]string{
		"region": cfg.Region,
	})
	if err != nil {
		// For now, create a mock provider for testing
		fmt.Printf("Note: Using mock provider (real provider not yet implemented)\n\n")
		p = provider.NewMockProvider(cfg.Provider, cfg.Region)
	}

	// Create planner
	plnr := planner.New(p)

	// Generate plan
	plan, err := plnr.PlanFromIntent(ctx, parsedIntent)
	if err != nil {
		return fmt.Errorf("failed to generate plan: %w", err)
	}

	// Display plan
	if outputFormat == "json" {
		fmt.Println(plan.ToJSON())
	} else {
		fmt.Println(plan.ToHumanReadable())
	}

	// Apply if requested
	if applyFlag {
		fmt.Println("\nApplying changes...")
		// TODO: Implement executor
		fmt.Println("Executor not yet implemented - this is a preview of what would happen")
	} else {
		fmt.Println("\nNote: This is a preview. Use --apply to make these changes.")
	}

	return nil
}

// executeFromConfig executes based on configuration file content
func executeFromConfig(ctx context.Context, cfg *config.Config) error {
	fmt.Println("Executing from configuration file...")
	
	// Get the provider
	p, err := provider.Get(cfg.Provider, map[string]string{
		"region": cfg.Region,
	})
	if err != nil {
		// For now, create a mock provider for testing
		fmt.Printf("Note: Using mock provider (real provider not yet implemented)\n\n")
		p = provider.NewMockProvider(cfg.Provider, cfg.Region)
	}

	// Create planner (for future use)
	_ = planner.New(p)

	// Process outcomes if they exist
	if len(cfg.Outcomes) > 0 {
		for name, outcome := range cfg.Outcomes {
			fmt.Printf("Processing outcome: %s\n", name)
			// For now, just show what would be planned
			fmt.Printf("- Type: %s\n", name)
			if outcome.Domain != "" {
				fmt.Printf("- Domain: %s\n", outcome.Domain)
			}
			if outcome.Runtime != "" {
				fmt.Printf("- Runtime: %s\n", outcome.Runtime)
			}
			fmt.Println()
		}
	}

	// Process resources if they exist
	if len(cfg.Resources.Compute) > 0 || len(cfg.Resources.Storage) > 0 || 
	   len(cfg.Resources.Database) > 0 || len(cfg.Resources.Serverless) > 0 {
		
		fmt.Println("Processing resources from configuration:")
		
		// Process compute resources
		for _, compute := range cfg.Resources.Compute {
			fmt.Printf("- Compute: %s (%s, count: %d)\n", compute.Name, compute.Type, compute.Count)
		}
		
		// Process storage resources  
		for _, storage := range cfg.Resources.Storage {
			fmt.Printf("- Storage: %s (%s)\n", storage.Name, storage.Type)
		}
		
		// Process database resources
		for _, database := range cfg.Resources.Database {
			fmt.Printf("- Database: %s (%s %s, %dGB)\n", database.Name, database.Engine, database.Size, database.Storage)
		}
		
		// Process serverless resources
		for _, serverless := range cfg.Resources.Serverless {
			fmt.Printf("- Function: %s (%s, %dMB)\n", serverless.Name, serverless.Runtime, serverless.Memory)
		}
		
		fmt.Println()
		fmt.Println("Note: Full resource execution from config not yet implemented")
	}

	return nil
}

// executeConfigFile handles execution of S3 and other config files
func executeConfigFile(ctx context.Context, configPath string) error {
	// Check if file exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return fmt.Errorf("configuration file does not exist: %s", configPath)
	}

	// Try to parse as S3 config first
	if isS3Config(configPath) {
		return executeS3Config(ctx, configPath)
	}

	// Try to parse as EC2 config
	if isEC2Config(configPath) {
		return executeEC2Config(ctx, configPath)
	}

	// Fall back to generic config execution
	fmt.Printf("Executing configuration file: %s\n", configPath)
	fmt.Println("Generic config execution not yet implemented")
	return nil
}

// isS3Config checks if the file is an S3 bucket configuration
func isS3Config(configPath string) bool {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return false
	}

	content := string(data)
	
	// Check for TOML format first
	if strings.HasSuffix(configPath, ".toml") {
		return (strings.Contains(content, "provider = \"aws\"") || strings.Contains(content, "provider=\"aws\"")) &&
			   (strings.Contains(content, "[[resources.storage]]") || strings.Contains(content, "storage") &&
			   (strings.Contains(content, "bucket") || strings.Contains(content, "type = \"bucket\"")))
	}
	
	// Fall back to YAML format
	return strings.Contains(content, "provider: aws") && 
		   strings.Contains(content, "storage:") && 
		   (strings.Contains(content, "bucket") || strings.Contains(content, "type: bucket"))
}

// isEC2Config checks if the file is an EC2 instance configuration
func isEC2Config(configPath string) bool {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return false
	}

	content := string(data)
	
	// Check for TOML format first
	if strings.HasSuffix(configPath, ".toml") {
		return (strings.Contains(content, "provider = \"aws\"") || strings.Contains(content, "provider=\"aws\"")) &&
			   (strings.Contains(content, "[[resources.compute]]") || strings.Contains(content, "compute") &&
			   (strings.Contains(content, "instance") || strings.Contains(content, "type = \"t3\"")))
	}
	
	// Fall back to YAML format
	return strings.Contains(content, "provider: aws") && 
		   strings.Contains(content, "compute:") && 
		   (strings.Contains(content, "instance") || strings.Contains(content, "type:"))
}

// executeS3Config handles S3 bucket configuration
func executeS3Config(ctx context.Context, configPath string) error {
	// Load S3 configuration
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read configuration file: %w", err)
	}

	var s3Config config.S3BucketConfig
	
	// Try to parse based on file extension
	if strings.HasSuffix(configPath, ".toml") {
		if err := toml.Unmarshal(data, &s3Config); err != nil {
			return fmt.Errorf("failed to parse S3 configuration as TOML: %w", err)
		}
	} else {
		// Fall back to YAML for backward compatibility
		if err := yaml.Unmarshal(data, &s3Config); err != nil {
			return fmt.Errorf("failed to parse S3 configuration as YAML: %w", err)
		}
	}

	bucketName := s3Config.Resources.Storage[0].Name
	
	if dryRunFlag {
		fmt.Printf("================================================================================\n")
		fmt.Printf("DRY RUN: S3 Bucket Creation Plan\n")
		fmt.Printf("Configuration: %s\n", configPath)
		fmt.Printf("================================================================================\n\n")
		
		fmt.Printf("RESOURCE TO CREATE:\n")
		fmt.Printf("  Type:         AWS S3 Bucket\n")
		fmt.Printf("  Name:         %s\n", bucketName)
		fmt.Printf("  Region:       %s\n", s3Config.Region)
		fmt.Printf("  ARN:          arn:aws:s3:::%s\n\n", bucketName)
		
		fmt.Printf("CONFIGURATION DETAILS:\n")
		fmt.Printf("  Versioning:   %s\n", formatBool(s3Config.Resources.Storage[0].Versioning, "Enabled", "Disabled"))
		fmt.Printf("  Encryption:   %s\n", formatBool(s3Config.Resources.Storage[0].Encryption, "AES256 (Server-Side)", "None"))
		fmt.Printf("  Public Access: %s\n", formatBool(s3Config.Resources.Storage[0].PublicAccess, "Allowed", "Blocked"))
		
		if len(s3Config.Resources.Storage[0].Tags) > 0 {
			fmt.Printf("\nRESOURCE TAGS:\n")
			for k, v := range s3Config.Resources.Storage[0].Tags {
				fmt.Printf("  %-15s: %s\n", k, v)
			}
		}
		
		if s3Config.Resources.Storage[0].Lifecycle != nil {
			fmt.Printf("\nLIFECYCLE RULES:\n")
			if s3Config.Resources.Storage[0].Lifecycle.DeleteAfterDays > 0 {
				fmt.Printf("  Delete After:   %d days\n", s3Config.Resources.Storage[0].Lifecycle.DeleteAfterDays)
			}
			if s3Config.Resources.Storage[0].Lifecycle.ArchiveAfterDays > 0 {
				fmt.Printf("  Archive After:  %d days (to Glacier)\n", s3Config.Resources.Storage[0].Lifecycle.ArchiveAfterDays)
			}
		}
		
		fmt.Printf("\nACTIONS THAT WOULD BE PERFORMED:\n")
		fmt.Printf("  1. Create S3 bucket '%s' in region %s\n", bucketName, s3Config.Region)
		if s3Config.Resources.Storage[0].Versioning {
			fmt.Printf("  2. Enable versioning on the bucket\n")
		}
		if s3Config.Resources.Storage[0].Encryption {
			fmt.Printf("  3. Enable AES256 encryption for all objects\n")
		}
		if !s3Config.Resources.Storage[0].PublicAccess {
			fmt.Printf("  4. Block all public access to the bucket\n")
		}
		if len(s3Config.Resources.Storage[0].Tags) > 0 {
			fmt.Printf("  5. Apply %d tags to the bucket\n", len(s3Config.Resources.Storage[0].Tags))
		}
		
		fmt.Printf("\n================================================================================\n")
		fmt.Printf("No actual changes will be made. Use --apply to create the resources.\n")
		fmt.Printf("================================================================================\n")
		return nil
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("APPLYING: S3 Bucket Creation\n")
	fmt.Printf("Configuration: %s\n", configPath)
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("Creating S3 Bucket:\n")
	fmt.Printf("  Name:   %s\n", bucketName)
	fmt.Printf("  Region: %s\n", s3Config.Region)
	fmt.Println()

	// Check AWS credentials
	interactiveConfig, err := config.NewInteractiveConfig()
	if err != nil {
		return fmt.Errorf("failed to initialize configuration: %w", err)
	}

	_, err = interactiveConfig.LoadProviderConfig("aws")
	if err != nil {
		return fmt.Errorf("AWS not configured. Run 'genesys config setup' to configure AWS credentials")
	}

	// Create AWS provider
	provider, err := aws.NewAWSProvider(s3Config.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS provider: %w", err)
	}

	// Get storage service
	storageService := provider.Storage()
	
	// Get bucket configuration
	bucketResource := s3Config.Resources.Storage[0]
	
	// Create bucket configuration
	bucketConf := &providerTypes.BucketConfig{
		Name:         bucketResource.Name,
		Versioning:   bucketResource.Versioning,
		Encryption:   bucketResource.Encryption,
		PublicAccess: bucketResource.PublicAccess,
		Tags:         bucketResource.Tags,
	}
	
	// Create bucket
	bucket, err := storageService.CreateBucket(ctx, bucketConf)
	if err != nil {
		return fmt.Errorf("failed to create S3 bucket: %w", err)
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("SUCCESS: S3 Bucket Created\n")
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("RESOURCE CREATED:\n")
	fmt.Printf("  Bucket Name:  %s\n", bucket.Name)
	fmt.Printf("  Region:       %s\n", s3Config.Region)
	fmt.Printf("  ARN:          arn:aws:s3:::%s\n", bucket.Name)
	fmt.Printf("  Created:      %s\n", bucket.CreatedAt.Format("2006-01-02 15:04:05 UTC"))
	
	fmt.Printf("\nCONFIGURATION APPLIED:\n")
	fmt.Printf("  Versioning:   %s\n", formatBool(s3Config.Resources.Storage[0].Versioning, "Enabled", "Disabled"))
	fmt.Printf("  Encryption:   %s\n", formatBool(s3Config.Resources.Storage[0].Encryption, "AES256 (Server-Side)", "None"))
	fmt.Printf("  Public Access: %s\n", formatBool(s3Config.Resources.Storage[0].PublicAccess, "Allowed", "Blocked"))
	
	if len(s3Config.Resources.Storage[0].Tags) > 0 {
		fmt.Printf("  Tags Applied: %d\n", len(s3Config.Resources.Storage[0].Tags))
	}
	
	fmt.Printf("\nNEXT STEPS:\n")
	fmt.Printf("  • View bucket contents: aws s3 ls s3://%s\n", bucketName)
	fmt.Printf("  • Upload files:         aws s3 cp <file> s3://%s/\n", bucketName)
	fmt.Printf("  • Delete bucket:        genesys execute deletion %s\n", configPath)
	fmt.Printf("\n================================================================================\n")

	return nil
}

// executeEC2Config handles EC2 instance configuration
func executeEC2Config(ctx context.Context, configPath string) error {
	// Load EC2 configuration
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read configuration file: %w", err)
	}

	var ec2Config config.EC2InstanceConfig
	
	// Try to parse based on file extension
	if strings.HasSuffix(configPath, ".toml") {
		if err := toml.Unmarshal(data, &ec2Config); err != nil {
			return fmt.Errorf("failed to parse EC2 configuration as TOML: %w", err)
		}
	} else {
		// Fall back to YAML for backward compatibility
		if err := yaml.Unmarshal(data, &ec2Config); err != nil {
			return fmt.Errorf("failed to parse EC2 configuration as YAML: %w", err)
		}
	}

	if len(ec2Config.Resources.Compute) == 0 {
		return fmt.Errorf("no compute resources found in configuration")
	}

	instanceName := ec2Config.Resources.Compute[0].Name
	
	if dryRunFlag {
		return performEC2DryRun(ctx, configPath, ec2Config)
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("APPLYING: EC2 Instance Creation\n")
	fmt.Printf("Configuration: %s\n", configPath)
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("Creating EC2 Instance:\n")
	fmt.Printf("  Name:   %s\n", instanceName)
	fmt.Printf("  Region: %s\n", ec2Config.Region)
	fmt.Printf("  Type:   %s\n", ec2Config.Resources.Compute[0].Type)
	fmt.Println()

	// Check AWS credentials
	interactiveConfig, err := config.NewInteractiveConfig()
	if err != nil {
		return fmt.Errorf("failed to initialize configuration: %w", err)
	}

	_, err = interactiveConfig.LoadProviderConfig("aws")
	if err != nil {
		return fmt.Errorf("AWS not configured. Run 'genesys config setup' to configure AWS credentials")
	}

	// Create AWS provider
	provider, err := aws.NewAWSProvider(ec2Config.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS provider: %w", err)
	}

	// Get compute service
	computeService := provider.Compute()
	
	// Get instance configuration
	instanceResource := ec2Config.Resources.Compute[0]
	
	// Create instance configuration
	instanceConf := &providerTypes.InstanceConfig{
		Name:  instanceResource.Name,
		Type:  providerTypes.InstanceType(instanceResource.Type),
		Image: instanceResource.Image,
		Tags:  instanceResource.Tags,
	}
	
	// Create instance
	instance, err := computeService.CreateInstance(ctx, instanceConf)
	if err != nil {
		return fmt.Errorf("failed to create EC2 instance: %w", err)
	}

	// Store in local state for tracking
	localState, err := state.LoadLocalState()
	if err != nil {
		fmt.Printf("Warning: Failed to load local state: %v\n", err)
	} else {
		record := state.ResourceRecord{
			ID:         instance.ID,
			Name:       instance.Name,
			Type:       "ec2",
			Region:     ec2Config.Region,
			Provider:   ec2Config.Provider,
			ConfigFile: configPath,
			CreatedAt:  time.Now(),
			Tags:       instanceResource.Tags,
		}
		
		if err := localState.AddResource(record); err != nil {
			fmt.Printf("Warning: Failed to save instance to local state: %v\n", err)
		} else {
			fmt.Printf("Instance tracked in local state: %s\n", instance.ID)
		}
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("SUCCESS: EC2 Instance Created\n")
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("RESOURCE CREATED:\n")
	fmt.Printf("  Instance ID:  %s\n", instance.ID)
	fmt.Printf("  Name:         %s\n", instance.Name)
	fmt.Printf("  Type:         %s\n", instance.Type)
	fmt.Printf("  State:        %s\n", instance.State)
	fmt.Printf("  Region:       %s\n", ec2Config.Region)
	fmt.Printf("  Private IP:   %s\n", instance.PrivateIP)
	fmt.Printf("  Created:      %s\n", instance.CreatedAt.Format("2006-01-02 15:04:05 UTC"))
	
	fmt.Printf("\nCONFIGURATION APPLIED:\n")
	fmt.Printf("  Instance Type: %s\n", ec2Config.Resources.Compute[0].Type)
	fmt.Printf("  AMI:          %s\n", ec2Config.Resources.Compute[0].Image)
	fmt.Printf("  Public IP:    %s\n", formatBool(ec2Config.Resources.Compute[0].PublicIP, "Assigned", "None"))
	
	if len(ec2Config.Resources.Compute[0].Tags) > 0 {
		fmt.Printf("  Tags Applied: %d\n", len(ec2Config.Resources.Compute[0].Tags))
	}
	
	// Add cost information to deployment output
	fmt.Printf("\n%s\n", strings.Repeat("-", 50))
	if estimate, err := config.EstimateEC2Costs(ec2Config.Resources.Compute[0], ec2Config.Region); err == nil {
		fmt.Printf("ESTIMATED COSTS:\n")
		fmt.Printf("  Monthly Cost: $%.2f/month ($%.4f/hour)\n", estimate.TotalMonthlyCost, estimate.HourlyRate)
		warningLevel := estimate.GetCostWarningLevel()
		switch warningLevel {
		case "HIGH":
			fmt.Printf("  HIGH COST WARNING: Monitor usage closely\n")
		case "MODERATE":
			fmt.Printf("  MODERATE COST: Set up billing alerts\n")
		case "LOW":
			fmt.Printf("  LOW COST: Cost-effective choice\n")
		}
	}
	fmt.Printf("%s\n", strings.Repeat("-", 50))
	
	fmt.Printf("\nNEXT STEPS:\n")
	fmt.Printf("  • View instance status: aws ec2 describe-instances --instance-ids %s\n", instance.ID)
	if ec2Config.Resources.Compute[0].KeyPair != "" {
		fmt.Printf("  • Connect via SSH:      ssh -i ~/.ssh/%s.pem ec2-user@<public-ip>\n", ec2Config.Resources.Compute[0].KeyPair)
	}
	fmt.Printf("  • Delete instance:      genesys execute deletion %s\n", configPath)
	fmt.Printf("\n================================================================================\n")

	return nil
}

// executeDeletion handles deletion of resources
func executeDeletion(ctx context.Context, configPath string) error {
	// Check if file exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return fmt.Errorf("configuration file does not exist: %s", configPath)
	}

	// Try to parse as S3 config first
	if isS3Config(configPath) {
		return executeS3Deletion(ctx, configPath)
	}

	// Try to parse as EC2 config
	if isEC2Config(configPath) {
		return executeEC2Deletion(ctx, configPath)
	}

	fmt.Printf("Deletion for configuration file '%s' not yet implemented\n", configPath)
	return nil
}

// executeS3Deletion handles S3 bucket deletion
func executeS3Deletion(ctx context.Context, configPath string) error {
	// Load S3 configuration
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read configuration file: %w", err)
	}

	var s3Config config.S3BucketConfig
	
	// Try to parse based on file extension
	if strings.HasSuffix(configPath, ".toml") {
		if err := toml.Unmarshal(data, &s3Config); err != nil {
			return fmt.Errorf("failed to parse S3 configuration as TOML: %w", err)
		}
	} else {
		// Fall back to YAML for backward compatibility
		if err := yaml.Unmarshal(data, &s3Config); err != nil {
			return fmt.Errorf("failed to parse S3 configuration as YAML: %w", err)
		}
	}

	bucketName := s3Config.Resources.Storage[0].Name

	if dryRunFlag {
		fmt.Printf("================================================================================\n")
		fmt.Printf("DRY RUN: S3 Bucket Deletion Plan\n")
		fmt.Printf("Configuration: %s\n", configPath)
		fmt.Printf("================================================================================\n\n")
		
		fmt.Printf("RESOURCE TO DELETE:\n")
		fmt.Printf("  Type:         AWS S3 Bucket\n")
		fmt.Printf("  Name:         %s\n", bucketName)
		fmt.Printf("  Region:       %s\n", s3Config.Region)
		fmt.Printf("  ARN:          arn:aws:s3:::%s\n\n", bucketName)
		
		fmt.Printf("ACTIONS THAT WOULD BE PERFORMED:\n")
		fmt.Printf("  1. Delete all objects in the bucket\n")
		fmt.Printf("  2. Remove all object versions (if versioning is enabled)\n")
		fmt.Printf("  3. Delete the bucket itself\n")
		
		fmt.Printf("\n⚠️  WARNING: This action is IRREVERSIBLE!\n")
		fmt.Printf("   All data in this bucket will be permanently lost.\n")
		
		fmt.Printf("\n================================================================================\n")
		fmt.Printf("No actual changes will be made. Use 'genesys execute deletion %s' to proceed.\n", configPath)
		fmt.Printf("================================================================================\n")
		return nil
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("APPLYING: S3 Bucket Deletion\n")
	fmt.Printf("Configuration: %s\n", configPath)
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("[WARNING] Deleting S3 Bucket:\n")
	fmt.Printf("  Name:   %s\n", bucketName)
	fmt.Printf("  Region: %s\n", s3Config.Region)
	fmt.Printf("  ARN:    arn:aws:s3:::%s\n\n", bucketName)
	
	fmt.Printf("This action cannot be undone!\n")
	fmt.Println("Proceeding with deletion...")

	// Create AWS provider
	provider, err := aws.NewAWSProvider(s3Config.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS provider: %w", err)
	}

	// Get storage service
	storageService := provider.Storage()

	// Delete bucket with force option if specified
	if forceDeletion {
		fmt.Printf("Force deletion mode enabled. This will delete all object versions and delete markers.\n")
		err = storageService.DeleteBucketWithOptions(ctx, bucketName, true)
	} else {
		err = storageService.DeleteBucket(ctx, bucketName)
	}
	
	if err != nil {
		// Check if error is already formatted (starts with bucket deletion failed)
		errStr := err.Error()
		if strings.Contains(errStr, "bucket deletion failed") {
			return fmt.Errorf("%s", errStr)
		}
		return fmt.Errorf("failed to delete S3 bucket: %w", err)
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("SUCCESS: S3 Bucket Deleted\n")
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("RESOURCE DELETED:\n")
	fmt.Printf("  Bucket Name:  %s\n", bucketName)
	fmt.Printf("  Region:       %s\n", s3Config.Region)
	fmt.Printf("  ARN:          arn:aws:s3:::%s\n", bucketName)
	
	fmt.Printf("\nThe bucket and all its contents have been permanently removed.\n")
	fmt.Printf("This action cannot be undone.\n")
	fmt.Printf("\n================================================================================\n")
	return nil
}

// executeEC2Deletion handles EC2 instance deletion
func executeEC2Deletion(ctx context.Context, configPath string) error {
	// Load EC2 configuration
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read configuration file: %w", err)
	}

	var ec2Config config.EC2InstanceConfig
	
	// Try to parse based on file extension
	if strings.HasSuffix(configPath, ".toml") {
		if err := toml.Unmarshal(data, &ec2Config); err != nil {
			return fmt.Errorf("failed to parse EC2 configuration as TOML: %w", err)
		}
	} else {
		// Fall back to YAML for backward compatibility
		if err := yaml.Unmarshal(data, &ec2Config); err != nil {
			return fmt.Errorf("failed to parse EC2 configuration as YAML: %w", err)
		}
	}

	if len(ec2Config.Resources.Compute) == 0 {
		return fmt.Errorf("no compute resources found in configuration")
	}

	instanceName := ec2Config.Resources.Compute[0].Name

	if dryRunFlag {
		fmt.Printf("================================================================================\n")
		fmt.Printf("DRY RUN: EC2 Instance Deletion Plan\n")
		fmt.Printf("Configuration: %s\n", configPath)
		fmt.Printf("================================================================================\n\n")
		
		fmt.Printf("RESOURCE TO DELETE:\n")
		fmt.Printf("  Type:         AWS EC2 Instance\n")
		fmt.Printf("  Name:         %s\n", instanceName)
		fmt.Printf("  Region:       %s\n", ec2Config.Region)
		fmt.Printf("  Instance Type: %s\n\n", ec2Config.Resources.Compute[0].Type)
		
		fmt.Printf("ACTIONS THAT WOULD BE PERFORMED:\n")
		fmt.Printf("  1. Find instances with Name tag '%s'\n", instanceName)
		fmt.Printf("  2. Stop running instances (if any)\n")
		fmt.Printf("  3. Terminate the instances\n")
		fmt.Printf("  4. Delete associated EBS volumes (if configured)\n")
		
		fmt.Printf("\nWARNING: This action is IRREVERSIBLE!\n")
		fmt.Printf("The instance and its data will be permanently lost.\n")
		
		fmt.Printf("\n================================================================================\n")
		fmt.Printf("No actual changes will be made. Use 'genesys execute deletion %s' to proceed.\n", configPath)
		fmt.Printf("================================================================================\n")
		return nil
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("APPLYING: EC2 Instance Deletion\n")
	fmt.Printf("Configuration: %s\n", configPath)
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("[WARNING] Deleting EC2 Instance:\n")
	fmt.Printf("  Name:   %s\n", instanceName)
	fmt.Printf("  Region: %s\n", ec2Config.Region)
	fmt.Printf("  Type:   %s\n\n", ec2Config.Resources.Compute[0].Type)
	
	fmt.Printf("This action cannot be undone!\n")
	fmt.Println("Proceeding with deletion...")

	// Create AWS provider
	provider, err := aws.NewAWSProvider(ec2Config.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS provider: %w", err)
	}

	// Get compute service
	computeService := provider.Compute()

	// Find instances with the matching name tag
	instances, err := computeService.ListInstances(ctx, map[string]string{
		"tag:Name": instanceName,
		"instance-state-name": "running,stopped,stopping,pending",
	})
	if err != nil {
		return fmt.Errorf("failed to list instances: %w", err)
	}

	if len(instances) == 0 {
		fmt.Printf("No instances found with Name tag '%s'.\n", instanceName)
		
		// Try to find instances from local state as fallback
		localState, err := state.LoadLocalState()
		if err == nil {
			stateInstances := localState.FindResourcesByConfigFile(configPath)
			if len(stateInstances) > 0 {
				fmt.Printf("Found %d instance(s) in local state for this config file:\n", len(stateInstances))
				for _, record := range stateInstances {
					fmt.Printf("  - %s (ID: %s, Created: %s)\n", record.Name, record.ID, record.CreatedAt.Format("2006-01-02 15:04:05"))
				}
				
				fmt.Printf("\nAttempting to delete instances found in local state...\n")
				
				// Try to delete each instance by ID
				for _, record := range stateInstances {
					fmt.Printf("Terminating instance from local state: %s\n", record.ID)
					
					if err := computeService.DeleteInstance(ctx, record.ID); err != nil {
						fmt.Printf("Warning: Failed to terminate instance %s: %v\n", record.ID, err)
						continue
					}
					
					// Remove from local state
					if err := localState.RemoveResource(record.ID); err != nil {
						fmt.Printf("Warning: Failed to remove %s from local state: %v\n", record.ID, err)
					} else {
						fmt.Printf("Removed %s from local state tracking\n", record.ID)
					}
				}
				
				fmt.Printf("\n================================================================================\n")
				fmt.Printf("SUCCESS: EC2 Instance(s) Terminated from Local State\n")
				fmt.Printf("================================================================================\n")
				return nil
			}
		}
		
		fmt.Printf("No instances found in AWS or local state. Nothing to delete.\n")
		return nil
	}

	// Load local state to update it
	localState, err := state.LoadLocalState()
	if err != nil {
		fmt.Printf("Warning: Failed to load local state: %v\n", err)
	}

	// Delete all matching instances
	for _, instance := range instances {
		fmt.Printf("Terminating instance: %s (%s)\n", instance.ID, instance.State)
		
		if err := computeService.DeleteInstance(ctx, instance.ID); err != nil {
			return fmt.Errorf("failed to terminate instance %s: %w", instance.ID, err)
		}
		
		// Remove from local state
		if localState != nil {
			if err := localState.RemoveResource(instance.ID); err != nil {
				fmt.Printf("Warning: Failed to remove %s from local state: %v\n", instance.ID, err)
			} else {
				fmt.Printf("Removed %s from local state tracking\n", instance.ID)
			}
		}
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("SUCCESS: EC2 Instance(s) Terminated\n")
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("RESOURCES TERMINATED:\n")
	for _, instance := range instances {
		fmt.Printf("  Instance ID:  %s\n", instance.ID)
		fmt.Printf("  Name:         %s\n", instance.Name)
		fmt.Printf("  Type:         %s\n", instance.Type)
	}
	fmt.Printf("  Region:       %s\n", ec2Config.Region)
	
	fmt.Printf("\nThe instance(s) are now terminating and will be permanently removed.\n")
	fmt.Printf("Associated EBS volumes may be deleted based on their configuration.\n")
	fmt.Printf("\n================================================================================\n")
	return nil
}

// performEC2DryRun performs actual AWS API validation for EC2 dry-run
func performEC2DryRun(ctx context.Context, configPath string, ec2Config config.EC2InstanceConfig) error {
	fmt.Printf("================================================================================\n")
	fmt.Printf("DRY RUN: EC2 Instance Creation Plan\n")
	fmt.Printf("Configuration: %s\n", configPath)
	fmt.Printf("================================================================================\n\n")
	
	instanceName := ec2Config.Resources.Compute[0].Name
	
	fmt.Printf("RESOURCE TO CREATE:\n")
	fmt.Printf("  Type:         AWS EC2 Instance\n")
	fmt.Printf("  Name:         %s\n", instanceName)
	fmt.Printf("  Region:       %s\n", ec2Config.Region)
	fmt.Printf("  Instance Type: %s\n", ec2Config.Resources.Compute[0].Type)
	fmt.Printf("  AMI:          %s\n", ec2Config.Resources.Compute[0].Image)
	
	fmt.Printf("\nVALIDATION RESULTS:\n")
	validationErrors := []string{}
	
	// Create AWS provider to validate
	provider, err := aws.NewAWSProvider(ec2Config.Region)
	if err != nil {
		validationErrors = append(validationErrors, fmt.Sprintf("AWS Provider: Failed to initialize (%v)", err))
	} else {
		fmt.Printf("  ✓ AWS Provider: Initialized successfully\n")
		
		// Validate credentials
		computeService := provider.Compute()
		
		// Test credentials by trying to list instances (this validates auth)
		fmt.Printf("  → Testing AWS credentials...\n")
		_, err := computeService.ListInstances(ctx, map[string]string{})
		if err != nil {
			validationErrors = append(validationErrors, fmt.Sprintf("AWS Credentials: Invalid or insufficient permissions (%v)", err))
		} else {
			fmt.Printf("  ✓ AWS Credentials: Valid and authenticated\n")
		}
		
		// Validate AMI
		fmt.Printf("  → Resolving and validating AMI...\n")
		
		// Initialize AMI resolver
		if computeService := provider.Compute(); computeService != nil {
			// Use reflection to access private method - let's use the actual creation flow
			amiID, err := validateAMIAccess(ctx, provider, ec2Config.Resources.Compute[0].Image, ec2Config.Region)
			if err != nil {
				validationErrors = append(validationErrors, fmt.Sprintf("AMI Resolution: %v", err))
			} else {
				fmt.Printf("  ✓ AMI: Resolved to %s and accessible\n", amiID)
			}
		}
		
		// Validate instance type (simplified check for known types)
		fmt.Printf("  → Validating instance type...\n")
		instanceType := ec2Config.Resources.Compute[0].Type
		knownTypes := []string{"t2.micro", "t3.micro", "t3.nano", "t3.small", "t3.medium", "t3.large", "t3.xlarge", "c7i-flex.large", "m7i-flex.large", "small", "medium", "large", "xlarge"}
		isKnownType := false
		for _, kt := range knownTypes {
			if instanceType == kt {
				isKnownType = true
				break
			}
		}
		if !isKnownType {
			validationErrors = append(validationErrors, fmt.Sprintf("Instance Type: '%s' is not a recognized instance type", instanceType))
		} else {
			fmt.Printf("  ✓ Instance Type: %s is a valid instance type\n", instanceType)
		}
	}
	
	// Show configuration details
	fmt.Printf("\nCONFIGURATION DETAILS:\n")
	fmt.Printf("  Public IP:    %s\n", formatBool(ec2Config.Resources.Compute[0].PublicIP, "Assigned", "None"))
	if ec2Config.Resources.Compute[0].KeyPair != "" {
		fmt.Printf("  Key Pair:     %s\n", ec2Config.Resources.Compute[0].KeyPair)
	}
	if ec2Config.Resources.Compute[0].Storage != nil {
		fmt.Printf("  Storage Size: %d GB\n", ec2Config.Resources.Compute[0].Storage.Size)
		fmt.Printf("  Volume Type:  %s\n", ec2Config.Resources.Compute[0].Storage.VolumeType)
		fmt.Printf("  Encrypted:    %s\n", formatBool(ec2Config.Resources.Compute[0].Storage.Encrypted, "Yes", "No"))
	}
	
	if len(ec2Config.Resources.Compute[0].Tags) > 0 {
		fmt.Printf("\nRESOURCE TAGS:\n")
		for k, v := range ec2Config.Resources.Compute[0].Tags {
			fmt.Printf("  %-15s: %s\n", k, v)
		}
	}
	
	// Show validation summary
	fmt.Printf("\n%s\n", strings.Repeat("=", 80))
	if len(validationErrors) == 0 {
		fmt.Printf("VALIDATION STATUS: ✓ ALL CHECKS PASSED\n")
		fmt.Printf("This configuration is ready for deployment.\n")
	} else {
		fmt.Printf("VALIDATION STATUS: ✗ %d ERROR(S) FOUND\n", len(validationErrors))
		fmt.Printf("The following issues must be resolved before deployment:\n")
		for i, err := range validationErrors {
			fmt.Printf("  %d. %s\n", i+1, err)
		}
	}
	
	// Add cost estimate
	fmt.Printf("\n%s\n", strings.Repeat("=", 80))
	if estimate, err := config.EstimateEC2Costs(ec2Config.Resources.Compute[0], ec2Config.Region); err == nil {
		fmt.Println(estimate.FormatCostEstimate())
	} else {
		fmt.Printf("Cost estimate unavailable: %v\n", err)
	}
	
	fmt.Printf("%s\n", strings.Repeat("=", 80))
	if len(validationErrors) == 0 {
		fmt.Printf("Ready to deploy! Use --apply to create the resources.\n")
	} else {
		fmt.Printf("Fix the validation errors above, then try again.\n")
	}
	fmt.Printf("================================================================================\n")
	
	return nil
}

// validateAMIAccess validates that the AMI can be resolved and is accessible
func validateAMIAccess(ctx context.Context, provider *aws.AWSProvider, image, region string) (string, error) {
	client, err := provider.CreateClient("ec2")
	if err != nil {
		return "", fmt.Errorf("failed to create EC2 client: %w", err)
	}
	
	resolver := aws.NewAMIResolver(provider, region)
	amiID, err := resolver.ResolveAMI(ctx, image)
	if err != nil {
		return "", fmt.Errorf("failed to resolve AMI '%s': %w", image, err)
	}
	
	// Additional validation: verify the AMI exists and is accessible
	params := map[string]string{
		"Action":    "DescribeImages",
		"ImageId.1": amiID,
	}
	
	resp, err := client.Request("POST", "/", params, nil)
	if err != nil {
		return "", fmt.Errorf("failed to validate AMI access: %w", err)
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("AMI %s not accessible (status: %d)", amiID, resp.StatusCode)
	}
	
	return amiID, nil
}

// validateInstanceType validates that the instance type is available in the region
func validateInstanceType(ctx context.Context, provider *aws.AWSProvider, instanceType, region string) error {
	client, err := provider.CreateClient("ec2")
	if err != nil {
		return fmt.Errorf("failed to create EC2 client: %w", err)
	}
	
	// Map the friendly name to AWS instance type
	var actualInstanceType string
	switch instanceType {
	case "small":
		actualInstanceType = "t3.small"
	case "medium":
		actualInstanceType = "t3.medium"
	case "large":
		actualInstanceType = "t3.large"
	case "xlarge":
		actualInstanceType = "t3.xlarge"
	case "t2.micro", "t3.micro", "t3.nano", "t2.small", "c7i-flex.large", "m7i-flex.large":
		actualInstanceType = instanceType
	default:
		actualInstanceType = "t3.micro" // Default
	}
	
	// Try to describe the instance type
	params := map[string]string{
		"Action":           "DescribeInstanceTypes",
		"InstanceTypes.1":  actualInstanceType,
		"MaxResults":       "1",
	}
	
	resp, err := client.Request("POST", "/", params, nil)
	if err != nil {
		return fmt.Errorf("failed to validate instance type: %w", err)
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != 200 {
		return fmt.Errorf("instance type %s not available in region %s", actualInstanceType, region)
	}
	
	return nil
}

// formatBool formats a boolean value with custom true/false labels
func formatBool(value bool, trueLabel, falseLabel string) string {
	if value {
		return trueLabel
	}
	return falseLabel
}