package commands

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/javanhut/genesys/pkg/config"
	"github.com/javanhut/genesys/pkg/intent"
	"github.com/javanhut/genesys/pkg/planner"
	"github.com/javanhut/genesys/pkg/provider"
	providerTypes "github.com/javanhut/genesys/pkg/provider"
	"github.com/javanhut/genesys/pkg/provider/aws"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	applyFlag       bool
	dryRunFlag      bool
	forceDeletion   bool
	configFile      string
	providerName    string
	region          string
	outputFormat    string
)

// NewExecuteCommand creates the execute command
func NewExecuteCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "execute [config-file.yaml | intent]",
		Short: "Deploy or delete resources from configuration files",
		Long: `Deploy or delete cloud resources from configuration files generated by interactive mode.
Supports dry-run for safe preview before deployment.

Examples:
  genesys execute config.yaml                           # Deploy resources from config
  genesys execute config.yaml --dry-run                 # Preview changes without deployment
  genesys execute deletion config.yaml                  # Delete resources from config
  genesys execute deletion config.yaml --dry-run        # Preview deletion
  genesys execute deletion config.yaml --force-deletion # Force delete including all versions

Legacy intent-based usage (for backwards compatibility):
  genesys execute bucket my-bucket --apply       # Create bucket from intent
  genesys execute static-site --apply            # Deploy static site`,
		Args: cobra.ArbitraryArgs,
		RunE: runExecute,
	}

	cmd.Flags().BoolVar(&applyFlag, "apply", false, "Apply the changes (default is preview only)")
	cmd.Flags().BoolVar(&dryRunFlag, "dry-run", false, "Show what would be done without making changes")
	cmd.Flags().BoolVar(&forceDeletion, "force-deletion", false, "Force delete bucket contents including all versions (use with deletion)")
	cmd.Flags().StringVarP(&configFile, "config", "c", "", "Configuration file (YAML or TOML)")
	cmd.Flags().StringVar(&providerName, "provider", "aws", "Cloud provider (aws|gcp|azure)")
	cmd.Flags().StringVar(&region, "region", "", "Cloud region")
	cmd.Flags().StringVarP(&outputFormat, "output", "o", "human", "Output format (human|json)")

	return cmd
}

func runExecute(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Handle special deletion case
	if len(args) >= 2 && args[0] == "deletion" {
		configFile = args[1]
		return executeDeletion(ctx, configFile)
	}

	// Handle direct config file execution (e.g., "genesys execute bucket.yaml")
	if len(args) == 1 && (strings.HasSuffix(args[0], ".yaml") || strings.HasSuffix(args[0], ".yml") || strings.HasSuffix(args[0], ".toml")) {
		configFile = args[0]
		return executeConfigFile(ctx, configFile)
	}

	// Load configuration if provided via --config flag
	var cfg *config.Config
	if configFile != "" {
		var err error
		cfg, err = config.LoadConfig(configFile)
		if err != nil {
			return fmt.Errorf("failed to load config: %w", err)
		}
	} else {
		// Create default config from flags
		cfg = &config.Config{
			Provider: providerName,
			Region:   region,
		}
	}

	// If we have a config file but no command line intent, execute based on config
	if configFile != "" && len(args) == 0 {
		return executeFromConfig(ctx, cfg)
	}

	// Parse the intent from command line arguments
	if len(args) == 0 {
		return fmt.Errorf("no intent specified. Usage: genesys execute <config-file.yaml> or genesys execute <intent>")
	}

	parser := intent.NewParser()
	parsedIntent, err := parser.Parse(args)
	if err != nil {
		return fmt.Errorf("failed to parse intent: %w", err)
	}

	// Get the provider
	p, err := provider.Get(cfg.Provider, map[string]string{
		"region": cfg.Region,
	})
	if err != nil {
		// For now, create a mock provider for testing
		fmt.Printf("Note: Using mock provider (real provider not yet implemented)\n\n")
		p = provider.NewMockProvider(cfg.Provider, cfg.Region)
	}

	// Create planner
	plnr := planner.New(p)

	// Generate plan
	plan, err := plnr.PlanFromIntent(ctx, parsedIntent)
	if err != nil {
		return fmt.Errorf("failed to generate plan: %w", err)
	}

	// Display plan
	if outputFormat == "json" {
		fmt.Println(plan.ToJSON())
	} else {
		fmt.Println(plan.ToHumanReadable())
	}

	// Apply if requested
	if applyFlag {
		fmt.Println("\nApplying changes...")
		// TODO: Implement executor
		fmt.Println("Executor not yet implemented - this is a preview of what would happen")
	} else {
		fmt.Println("\nNote: This is a preview. Use --apply to make these changes.")
	}

	return nil
}

// executeFromConfig executes based on configuration file content
func executeFromConfig(ctx context.Context, cfg *config.Config) error {
	fmt.Println("Executing from configuration file...")
	
	// Get the provider
	p, err := provider.Get(cfg.Provider, map[string]string{
		"region": cfg.Region,
	})
	if err != nil {
		// For now, create a mock provider for testing
		fmt.Printf("Note: Using mock provider (real provider not yet implemented)\n\n")
		p = provider.NewMockProvider(cfg.Provider, cfg.Region)
	}

	// Create planner (for future use)
	_ = planner.New(p)

	// Process outcomes if they exist
	if len(cfg.Outcomes) > 0 {
		for name, outcome := range cfg.Outcomes {
			fmt.Printf("Processing outcome: %s\n", name)
			// For now, just show what would be planned
			fmt.Printf("- Type: %s\n", name)
			if outcome.Domain != "" {
				fmt.Printf("- Domain: %s\n", outcome.Domain)
			}
			if outcome.Runtime != "" {
				fmt.Printf("- Runtime: %s\n", outcome.Runtime)
			}
			fmt.Println()
		}
	}

	// Process resources if they exist
	if len(cfg.Resources.Compute) > 0 || len(cfg.Resources.Storage) > 0 || 
	   len(cfg.Resources.Database) > 0 || len(cfg.Resources.Serverless) > 0 {
		
		fmt.Println("Processing resources from configuration:")
		
		// Process compute resources
		for _, compute := range cfg.Resources.Compute {
			fmt.Printf("- Compute: %s (%s, count: %d)\n", compute.Name, compute.Type, compute.Count)
		}
		
		// Process storage resources  
		for _, storage := range cfg.Resources.Storage {
			fmt.Printf("- Storage: %s (%s)\n", storage.Name, storage.Type)
		}
		
		// Process database resources
		for _, database := range cfg.Resources.Database {
			fmt.Printf("- Database: %s (%s %s, %dGB)\n", database.Name, database.Engine, database.Size, database.Storage)
		}
		
		// Process serverless resources
		for _, serverless := range cfg.Resources.Serverless {
			fmt.Printf("- Function: %s (%s, %dMB)\n", serverless.Name, serverless.Runtime, serverless.Memory)
		}
		
		fmt.Println()
		fmt.Println("Note: Full resource execution from config not yet implemented")
	}

	return nil
}

// executeConfigFile handles execution of S3 and other config files
func executeConfigFile(ctx context.Context, configPath string) error {
	// Check if file exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return fmt.Errorf("configuration file does not exist: %s", configPath)
	}

	// Try to parse as S3 config first
	if isS3Config(configPath) {
		return executeS3Config(ctx, configPath)
	}

	// Fall back to generic config execution
	fmt.Printf("Executing configuration file: %s\n", configPath)
	fmt.Println("Generic config execution not yet implemented")
	return nil
}

// isS3Config checks if the file is an S3 bucket configuration
func isS3Config(configPath string) bool {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return false
	}

	content := string(data)
	
	// Check for TOML format first
	if strings.HasSuffix(configPath, ".toml") {
		return (strings.Contains(content, "provider = \"aws\"") || strings.Contains(content, "provider=\"aws\"")) &&
			   (strings.Contains(content, "[[resources.storage]]") || strings.Contains(content, "storage") &&
			   (strings.Contains(content, "bucket") || strings.Contains(content, "type = \"bucket\"")))
	}
	
	// Fall back to YAML format
	return strings.Contains(content, "provider: aws") && 
		   strings.Contains(content, "storage:") && 
		   (strings.Contains(content, "bucket") || strings.Contains(content, "type: bucket"))
}

// executeS3Config handles S3 bucket configuration
func executeS3Config(ctx context.Context, configPath string) error {
	// Load S3 configuration
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read configuration file: %w", err)
	}

	var s3Config config.S3BucketConfig
	
	// Try to parse based on file extension
	if strings.HasSuffix(configPath, ".toml") {
		if err := toml.Unmarshal(data, &s3Config); err != nil {
			return fmt.Errorf("failed to parse S3 configuration as TOML: %w", err)
		}
	} else {
		// Fall back to YAML for backward compatibility
		if err := yaml.Unmarshal(data, &s3Config); err != nil {
			return fmt.Errorf("failed to parse S3 configuration as YAML: %w", err)
		}
	}

	bucketName := s3Config.Resources.Storage[0].Name
	
	if dryRunFlag {
		fmt.Printf("================================================================================\n")
		fmt.Printf("DRY RUN: S3 Bucket Creation Plan\n")
		fmt.Printf("Configuration: %s\n", configPath)
		fmt.Printf("================================================================================\n\n")
		
		fmt.Printf("RESOURCE TO CREATE:\n")
		fmt.Printf("  Type:         AWS S3 Bucket\n")
		fmt.Printf("  Name:         %s\n", bucketName)
		fmt.Printf("  Region:       %s\n", s3Config.Region)
		fmt.Printf("  ARN:          arn:aws:s3:::%s\n\n", bucketName)
		
		fmt.Printf("CONFIGURATION DETAILS:\n")
		fmt.Printf("  Versioning:   %s\n", formatBool(s3Config.Resources.Storage[0].Versioning, "Enabled", "Disabled"))
		fmt.Printf("  Encryption:   %s\n", formatBool(s3Config.Resources.Storage[0].Encryption, "AES256 (Server-Side)", "None"))
		fmt.Printf("  Public Access: %s\n", formatBool(s3Config.Resources.Storage[0].PublicAccess, "Allowed", "Blocked"))
		
		if len(s3Config.Resources.Storage[0].Tags) > 0 {
			fmt.Printf("\nRESOURCE TAGS:\n")
			for k, v := range s3Config.Resources.Storage[0].Tags {
				fmt.Printf("  %-15s: %s\n", k, v)
			}
		}
		
		if s3Config.Resources.Storage[0].Lifecycle != nil {
			fmt.Printf("\nLIFECYCLE RULES:\n")
			if s3Config.Resources.Storage[0].Lifecycle.DeleteAfterDays > 0 {
				fmt.Printf("  Delete After:   %d days\n", s3Config.Resources.Storage[0].Lifecycle.DeleteAfterDays)
			}
			if s3Config.Resources.Storage[0].Lifecycle.ArchiveAfterDays > 0 {
				fmt.Printf("  Archive After:  %d days (to Glacier)\n", s3Config.Resources.Storage[0].Lifecycle.ArchiveAfterDays)
			}
		}
		
		fmt.Printf("\nACTIONS THAT WOULD BE PERFORMED:\n")
		fmt.Printf("  1. Create S3 bucket '%s' in region %s\n", bucketName, s3Config.Region)
		if s3Config.Resources.Storage[0].Versioning {
			fmt.Printf("  2. Enable versioning on the bucket\n")
		}
		if s3Config.Resources.Storage[0].Encryption {
			fmt.Printf("  3. Enable AES256 encryption for all objects\n")
		}
		if !s3Config.Resources.Storage[0].PublicAccess {
			fmt.Printf("  4. Block all public access to the bucket\n")
		}
		if len(s3Config.Resources.Storage[0].Tags) > 0 {
			fmt.Printf("  5. Apply %d tags to the bucket\n", len(s3Config.Resources.Storage[0].Tags))
		}
		
		fmt.Printf("\n================================================================================\n")
		fmt.Printf("No actual changes will be made. Use --apply to create the resources.\n")
		fmt.Printf("================================================================================\n")
		return nil
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("APPLYING: S3 Bucket Creation\n")
	fmt.Printf("Configuration: %s\n", configPath)
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("Creating S3 Bucket:\n")
	fmt.Printf("  Name:   %s\n", bucketName)
	fmt.Printf("  Region: %s\n", s3Config.Region)
	fmt.Println()

	// Check AWS credentials
	interactiveConfig, err := config.NewInteractiveConfig()
	if err != nil {
		return fmt.Errorf("failed to initialize configuration: %w", err)
	}

	_, err = interactiveConfig.LoadProviderConfig("aws")
	if err != nil {
		return fmt.Errorf("AWS not configured. Run 'genesys config setup' to configure AWS credentials")
	}

	// Create AWS provider
	provider, err := aws.NewAWSProvider(s3Config.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS provider: %w", err)
	}

	// Get storage service
	storageService := provider.Storage()
	
	// Get bucket configuration
	bucketResource := s3Config.Resources.Storage[0]
	
	// Create bucket configuration
	bucketConf := &providerTypes.BucketConfig{
		Name:         bucketResource.Name,
		Versioning:   bucketResource.Versioning,
		Encryption:   bucketResource.Encryption,
		PublicAccess: bucketResource.PublicAccess,
		Tags:         bucketResource.Tags,
	}
	
	// Create bucket
	bucket, err := storageService.CreateBucket(ctx, bucketConf)
	if err != nil {
		return fmt.Errorf("failed to create S3 bucket: %w", err)
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("SUCCESS: S3 Bucket Created\n")
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("RESOURCE CREATED:\n")
	fmt.Printf("  Bucket Name:  %s\n", bucket.Name)
	fmt.Printf("  Region:       %s\n", s3Config.Region)
	fmt.Printf("  ARN:          arn:aws:s3:::%s\n", bucket.Name)
	fmt.Printf("  Created:      %s\n", bucket.CreatedAt.Format("2006-01-02 15:04:05 UTC"))
	
	fmt.Printf("\nCONFIGURATION APPLIED:\n")
	fmt.Printf("  Versioning:   %s\n", formatBool(s3Config.Resources.Storage[0].Versioning, "Enabled", "Disabled"))
	fmt.Printf("  Encryption:   %s\n", formatBool(s3Config.Resources.Storage[0].Encryption, "AES256 (Server-Side)", "None"))
	fmt.Printf("  Public Access: %s\n", formatBool(s3Config.Resources.Storage[0].PublicAccess, "Allowed", "Blocked"))
	
	if len(s3Config.Resources.Storage[0].Tags) > 0 {
		fmt.Printf("  Tags Applied: %d\n", len(s3Config.Resources.Storage[0].Tags))
	}
	
	fmt.Printf("\nNEXT STEPS:\n")
	fmt.Printf("  • View bucket contents: aws s3 ls s3://%s\n", bucketName)
	fmt.Printf("  • Upload files:         aws s3 cp <file> s3://%s/\n", bucketName)
	fmt.Printf("  • Delete bucket:        genesys execute deletion %s\n", configPath)
	fmt.Printf("\n================================================================================\n")

	return nil
}

// executeDeletion handles deletion of resources
func executeDeletion(ctx context.Context, configPath string) error {
	// Check if file exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return fmt.Errorf("configuration file does not exist: %s", configPath)
	}

	// Try to parse as S3 config first
	if isS3Config(configPath) {
		return executeS3Deletion(ctx, configPath)
	}

	fmt.Printf("Deletion for configuration file '%s' not yet implemented\n", configPath)
	return nil
}

// executeS3Deletion handles S3 bucket deletion
func executeS3Deletion(ctx context.Context, configPath string) error {
	// Load S3 configuration
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read configuration file: %w", err)
	}

	var s3Config config.S3BucketConfig
	
	// Try to parse based on file extension
	if strings.HasSuffix(configPath, ".toml") {
		if err := toml.Unmarshal(data, &s3Config); err != nil {
			return fmt.Errorf("failed to parse S3 configuration as TOML: %w", err)
		}
	} else {
		// Fall back to YAML for backward compatibility
		if err := yaml.Unmarshal(data, &s3Config); err != nil {
			return fmt.Errorf("failed to parse S3 configuration as YAML: %w", err)
		}
	}

	bucketName := s3Config.Resources.Storage[0].Name

	if dryRunFlag {
		fmt.Printf("================================================================================\n")
		fmt.Printf("DRY RUN: S3 Bucket Deletion Plan\n")
		fmt.Printf("Configuration: %s\n", configPath)
		fmt.Printf("================================================================================\n\n")
		
		fmt.Printf("RESOURCE TO DELETE:\n")
		fmt.Printf("  Type:         AWS S3 Bucket\n")
		fmt.Printf("  Name:         %s\n", bucketName)
		fmt.Printf("  Region:       %s\n", s3Config.Region)
		fmt.Printf("  ARN:          arn:aws:s3:::%s\n\n", bucketName)
		
		fmt.Printf("ACTIONS THAT WOULD BE PERFORMED:\n")
		fmt.Printf("  1. Delete all objects in the bucket\n")
		fmt.Printf("  2. Remove all object versions (if versioning is enabled)\n")
		fmt.Printf("  3. Delete the bucket itself\n")
		
		fmt.Printf("\n⚠️  WARNING: This action is IRREVERSIBLE!\n")
		fmt.Printf("   All data in this bucket will be permanently lost.\n")
		
		fmt.Printf("\n================================================================================\n")
		fmt.Printf("No actual changes will be made. Use 'genesys execute deletion %s' to proceed.\n", configPath)
		fmt.Printf("================================================================================\n")
		return nil
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("APPLYING: S3 Bucket Deletion\n")
	fmt.Printf("Configuration: %s\n", configPath)
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("[WARNING] Deleting S3 Bucket:\n")
	fmt.Printf("  Name:   %s\n", bucketName)
	fmt.Printf("  Region: %s\n", s3Config.Region)
	fmt.Printf("  ARN:    arn:aws:s3:::%s\n\n", bucketName)
	
	fmt.Printf("⚠️  This action cannot be undone!\n")
	fmt.Println("Proceeding with deletion...")

	// Create AWS provider
	provider, err := aws.NewAWSProvider(s3Config.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS provider: %w", err)
	}

	// Get storage service
	storageService := provider.Storage()

	// Delete bucket with force option if specified
	if forceDeletion {
		fmt.Printf("Force deletion mode enabled. This will delete all object versions and delete markers.\n")
		err = storageService.DeleteBucketWithOptions(ctx, bucketName, true)
	} else {
		err = storageService.DeleteBucket(ctx, bucketName)
	}
	
	if err != nil {
		// Check if error is already formatted (starts with bucket deletion failed)
		errStr := err.Error()
		if strings.Contains(errStr, "bucket deletion failed") {
			return fmt.Errorf("%s", errStr)
		}
		return fmt.Errorf("failed to delete S3 bucket: %w", err)
	}

	fmt.Printf("================================================================================\n")
	fmt.Printf("SUCCESS: S3 Bucket Deleted\n")
	fmt.Printf("================================================================================\n\n")
	
	fmt.Printf("RESOURCE DELETED:\n")
	fmt.Printf("  Bucket Name:  %s\n", bucketName)
	fmt.Printf("  Region:       %s\n", s3Config.Region)
	fmt.Printf("  ARN:          arn:aws:s3:::%s\n", bucketName)
	
	fmt.Printf("\nThe bucket and all its contents have been permanently removed.\n")
	fmt.Printf("This action cannot be undone.\n")
	fmt.Printf("\n================================================================================\n")
	return nil
}

// formatBool formats a boolean value with custom true/false labels
func formatBool(value bool, trueLabel, falseLabel string) string {
	if value {
		return trueLabel
	}
	return falseLabel
}